---
title: 'DATA698 Final Research Project '
author: "Christian Thieme"
date: "12/10/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(VIM)
library(mice)
```

## Abstract

This section will be written last after final results are available

## Introduction

Sports analytics has grown exponentially in the last decade. The success of "Moneyball" type analytics in baseball has led to many other sports attempting to find an edge using analytics. Sports teams around the country, both professional and collegiate, employ full time analysts to try and squeeze out any ounce of improvement for their teams that they can. Another area in the sports arena that has grown tremendously over the last 10 years are fans involvement in "fantasy" leagues. These leagues allow the individual to "draft" players on to their team and then are given points each week based on the performance of the players in the team. The fantasy football following is the largest of all the fantasy sports. While these leagues may sound silly to some, there are millions of people who play and there is **big** money involved. The NFL's biggest prize is \$1,000,000 (Subramanian, 2014).

More and more people are turning from using their gut, to really diving into the analytics of players and teams (Koss, 2020). In a special kind of league called a dynasty league, participants are allowed to keep their players year after year. That means that a major way to improve your standings each year is to draft the right rookies on to your team as players transition from college to the NFL. One of the positions that can have a huge impact on a dynasty team as a rookie is that of the wide receiver.

Each year, dozens of sports analysts make predictions about who the "break out" wide receivers will be based on having watched their college careers. Often the analysts get the obvious players right, but each year there are also surprises and disappointments. Is there a more quantitative way to determine who these breakout players will be?

Answering that question is the purpose of this research project. This project will seek to build a predictive model using a wide receiver's collegiate and NFL combine statistics to accurately predict 80% of the wide receivers that will average 10 fantasy points per game.

## Literature Review

There is little to no academic research in the way of determining break out players in the NFL as it relates to NFL Fantasy leagues. Because having an accurate predictive model in this arena can be extremely lucrative, those who have managed to build such models have done so privately and either charge money to use it, or make money by using it themselves.

While there are articles that discuss what age a player will be when they "break out", they are talked about in an extremely high level fashion without describing any specifics as to the data, the methods, or the model. In fact, most articles won't share more than an r-squared value. Further, when articles do share an r-squared value, it hints that more simple regression type models are being used as opposed to more leading edge, advanced algorithms.

Besides the fact that keeping these models as proprietary property can be "good business", we can also attribute some of the lack of research to the fact that the NFL has historically had the least amount of data available to the public (Lindsey, 2016). The league has only recently found value in tracking and sharing more data, which has led to much of the analytics explosion within the NFL.

## Hypothesis

In this study, I will determine if it is possible to build a predictive model using a wide receiver's collegiate and NFL combine statistics to accurately predict 80% of the wide receivers that will average 10 fantasy points per game.

## Data and Variables

As mentioned previously, there are very few places where you can get extensive historical collegiate data for players who now or did play in the NFL. There are of course popular websites that host basic statistics for each player's collegiate stats, but these statistics are the basic metrics such as yards, touchdowns, etc. Those who are familiar with fantasy football know that each of these metrics can be broken down into many, many more metrics, and combinations of these metrics can lead to hundreds more.

The data source I will use for this project, is perhaps the only one of its kind. It contains hundreds of variables for each player and is maintained by Dave Wright who is a well-known author at DynastyLeagueFootball.com (Wright, n.d.). He provides this dataset free of charge in an effort to help evangelize analytics in fantasy football. It contains player statistics from the 2018-2022 seasons. The dataset also is unique in that it is broken down exclusively into players who are wide receivers. There are 836 rows (players) in the dataset and 602 columns. The dataset contains both numeric and categorical data.

For each player in the dataset, there are several descriptive columns that have critical information for each player and don't contain missing data. These columns are:

-   Player Name

-   School - college they attended

-   Conference - the athletic conference the school is in

-   Date of Birth (DOB)

-   Draft Round - the round the player was selected in the NFL draft (there are 7 rounds)

-   Draft Pick - what number the player was selected overall in the draft

-   Draft Year

-   Draft Age - how old the player was when they were drafter

-   NCAA Seasons - how many seasons they played in the NFL

Following these columns, there are three types of numeric columns: yearly statistics from the 2018-2022 seasons, aggregated metrics from these seasons such as average receptions per game or total career touch downs, and metrics from the NFL combine such as height, weight, 40 time, hand size, etc. In total, there are 100 different metrics. Some of these metrics are straight forward and well known, others are rather specific and are derived from calculations of other columns. A full listing of metrics within the dataset are presented below as well as their definition, the type of metric it is (if it is from a season, a count, from the combine, etc.) and how they are calculated:

+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| Term                             | Abbreviations              | Type     | Definition                                                                                                                                                                                                                                  | Formula                                                                       |
+==================================+============================+==========+=============================================================================================================================================================================================================================================+===============================================================================+
| **20 Yard Shuttle**              | **Shuttle,                 | Combine  | measures an player's lateral quickness by having the player move laterally 5 yards to                                                                                                                                                       | \-                                                                            |
|                                  | Short Shuttle**            |          | touch a line, then 10 yards to the left to touch a line, and finally 5 yards to the right to finish.                                                                                                                                        |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **3 Cone Drill**                 | **3 Cone**                 | Combine  | measures a player's ability to change directions as they run around 3 cones placed in                                                                                                                                                       | \-                                                                            |
|                                  |                            |          | an L-shape.                                                                                                                                                                                                                                 |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **40                             | **-**                      | Combine  | a sprint measuring 40 yards. Times not recorded at the NFL combine are adjusted                                                                                                                                                             | \-                                                                            |
| Time**                           |                            |          | by adding .05 seconds to the player time.                                                                                                                                                                                                   |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Adjusted                       | **AY/A, AYA**              | Metric   | created by Bob Carroll, Pete Palmer, and Jim Thorn in The Hidden Game of Football\* to                                                                                                                                                      | (Pass YDs + 20\*(Pass TD) - 45\*(INT))/(Pass ATTs)                            |
| Yards Per Attempt**              |                            |          | weight the significance of Pass TDs, Pass Yds, and INT when considering Y/PA.                                                                                                                                                               |                                                                               |
|                                  |                            |          | \*source Pro Football Reference.                                                                                                                                                                                                            |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Agility                        | **-**                      | Combine  | a metric intended to measure a player's lateral agility and quickness                                                                                                                                                                       | Shuttle + 3 Cone                                                              |
| Score**                          |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Arm                            | **-**                      | Combine  | the distance from the end of the bicep or shoulder blade to the tip of the middle                                                                                                                                                           | \-                                                                            |
| Length**                         |                            |          | finger with the arm extended.                                                                                                                                                                                                               |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Bench                          | **Bench**                  | Combine  | measures the amount of reps a player can lift 225 lbs in the bench press lifting                                                                                                                                                            | \-                                                                            |
| Press**                          |                            |          | exercise.                                                                                                                                                                                                                                   |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Body Mass Index**              | **BMI**                    | Combine  | an index of an individual's weight compared to their height to describe someone's level of thickness. Derived by Belgian Adolphe Quetelet.                                                                                                  | "=((weight                                                                    |
|                                  |                            |          |                                                                                                                                                                                                                                             | in pounds/height in inches)\*703)"                                            |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Breakout                       | **BOA**                    | Metric   | a metric created by Frank Dupont and Shawn Siegele where a player's production                                                                                                                                                              | "stat/metric\>threshold"                                                      |
| Age**                            |                            |          | eclipses a certain threshold to represent they have become a significant                                                                                                                                                                    |                                                                               |
|                                  |                            |          | contributor for their college team                                                                                                                                                                                                          |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Broad                          | **Broad**                  | Combine  | measures the player's ability to jump horizontally from a balanced stance.                                                                                                                                                                  | \-                                                                            |
| Jump**                           |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Career Average**               | **-**                      | \-       | the college career average of a stat or metric for a player.                                                                                                                                                                                | "=AVERAGE(cell                                                                |
|                                  |                            |          |                                                                                                                                                                                                                                             | for age 18 szn:cell for age 23 szn)"                                          |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Career                         | **-**                      | \-       | a stat or metric's "best" value in a particular season. For TDs it                                                                                                                                                                          | "=MAX(cell                                                                    |
| Best**                           |                            |          | would be the highest value and for INTs it would be the lowest value.                                                                                                                                                                       | for age 18 szn:cell for age 23 szn)"                                          |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Career                         | **-**                      | \-       | the value of a stat or metric from the last season of a player's college career.                                                                                                                                                            | "=LOOKUP(9999999999,(cell                                                     |
| Last**                           |                            |          |                                                                                                                                                                                                                                             | for age 18 szn:cell for age 23 szn)"                                          |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Career                         | **-**                      | Counting | the total counting stat for a player's college career                                                                                                                                                                                       | \-                                                                            |
| Total**                          |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **College                        | **CD, DOM**                | Metric   | metric originated by Frank DuPont in his book Game Plan, it represents the player's                                                                                                                                                         | "=(Career                                                                     |
| Dominator**                      |                            |          | percentage of their team's offense in respect to the team's yardage and                                                                                                                                                                     | Last + Career Best)/2"                                                        |
|                                  |                            |          | touchdowns.                                                                                                                                                                                                                                 |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Combine                        | **COMB SCRIM MS**          | Metric   | a metric designed to represent a player's total offensive production within their offense.                                                                                                                                                  | ((SCRIM                                                                       |
| Scrimmage Market Share**         |                            |          |                                                                                                                                                                                                                                             | YDs/TM SCRIM Yds)+(SCRIM TDs/TM SCRIM TDs)/2)                                 |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Combined                       | **COMB QB MS**             | Metric   | a metric designed to represent a QBs production in their team's passing offense.                                                                                                                                                            | ((Pass                                                                        |
| QB Market Share**                |                            |          |                                                                                                                                                                                                                                             | YDs/TM Pass Yds)/2)+((Pass TDs/TM Pass TDs)/2))                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Combined                       | **QB COMB TM %**           | Metric   | the percentage of the team yards that were Pass YDs by a player divided by two                                                                                                                                                              | ((Pass                                                                        |
| QB Team %**                      |                            |          | added to the percentage of the team TDs that were Pass TDs by a player divided by two.                                                                                                                                                      | YDs/TM Yds)/2+(Pass TDs/TM TDs)2)                                             |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Combined                       | **Comb REC MS**            | Metric   | a metric designed to represent a player's receiving production in their college offense                                                                                                                                                     | ((REC                                                                         |
| Receiving Market Share**         |                            |          |                                                                                                                                                                                                                                             | YDs/TM REC Yds)/2)+((REC TDs/TM REC TDs)/2))                                  |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Combined                       | **COMB Rush MS**           | Metric   | a metric designed to represent a QBs production in their team's rushing offense.                                                                                                                                                            | ((Rush                                                                        |
| Rush Market Share**              |                            |          |                                                                                                                                                                                                                                             | YDs/TM Rush Yds)/2)+((Rush TDs/TM Rush TDs)/2))                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Conference**                   | **Conf**                   | Bio      | the college football conference of the team a player played for in their last year of college football. (Non-CFB means non Division 1 schools)                                                                                              | \-                                                                            |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Fantasy                        | **PPR                      | Metric   |                                                                                                                                                                                                                                             | (REC)+(scrimmage                                                              |
| Points**                         | Points**                   |          |                                                                                                                                                                                                                                             | yards\*.1)+(Total TDs\*6)                                                     |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Freak                          | **-**                      | Combine  | an athleticism metric that accounts for the height, weight, and speed of a prospect                                                                                                                                                         | \-                                                                            |
| Score**                          |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Games                          | **GP**                     | Counting | player makes appearance on the field regardless of position.                                                                                                                                                                                | \-                                                                            |
| Played**                         |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Hand                           | **-**                      | Combine  | the distance from the tip of the pinky to the tip of the thumb with the fingers spread out                                                                                                                                                  | \-                                                                            |
| Size**                           |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Height**                       | **-**                      | Combine  | the amount of distance from the bottom of a player's heals to the top of their head In inches.                                                                                                                                              | \-                                                                            |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Interception                   | **INT %**                  | Metric   | Interceptions divided by Pass ATTs                                                                                                                                                                                                          | INT/Pass ATTs                                                                 |
| %**                              |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Kick                           | **Kick Returns**           | Counting | when a player receives a kickoff from the opposing team and attempts to advance the ball down the field.                                                                                                                                    | \-                                                                            |
| Return**                         |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Kick                           | **KR TDs**                 | Counting | when a kick return results in a touchdown for the team that receives it.                                                                                                                                                                    | \-                                                                            |
| Return Touchdown**               |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Kick                           | **KR YDs**                 | Counting | the yards a player gains after receiving a kickoff from the opposing team                                                                                                                                                                   | \-                                                                            |
| Return Yard**                    |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Over                           | **OVR AVG**                | Metric   | a stat or metric over the average of certain cohort of players at that player's position.                                                                                                                                                   | \-                                                                            |
| Average**                        |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Over                           | **OVR EXP**                | Metric   | a stat or metric over the average of that stat or metric for the player's in that conference.                                                                                                                                               | \-                                                                            |
| Expected**                       |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Over                           | **Over TM AVG**            | Metric   | a stat or metric compared to the player's college team performance for the same stat or metric.                                                                                                                                             | stat/metrcic                                                                  |
| Team Average**                   |                            |          |                                                                                                                                                                                                                                             | minus the college team's performance in that stat/metric for the season       |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass ATT, PA**           | Counting | offensive player throws the ball forward when behind line of scrimmage.                                                                                                                                                                     | \-                                                                            |
| Attempt**                        |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass ATT % of TM Plays** | Metric   | the percentage of the team plays that were Pass ATTs by a player.                                                                                                                                                                           | Pass ATT/TM Plays                                                             |
| Attempt % of Team Plays**        |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass CD**                | Metric   | a metric that equally weighs the career last and career best seasons in terms                                                                                                                                                               | "=((Career                                                                    |
| College Dominator**              |                            |          | of market share of team yards and touchdowns.                                                                                                                                                                                               | Last QB COMB TM %+Career Best QB COMB TM %)/2)"                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Comp %**                 | Metric   | Pass Completions divided by pass attempts                                                                                                                                                                                                   | Pass Comp/Pass ATTs                                                           |
| Completion Percentage**          |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **INT**                    | Counting | opposing defense catches a pass attempt by the offense.                                                                                                                                                                                     | \-                                                                            |
| Interceptions**                  |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass TD %**              | Metric   | Pass TDs divided by Pass ATTs                                                                                                                                                                                                               | Pass TDs/Pass ATTs                                                            |
| TD %**                           |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass TDs % of Team TDs** | Metric   | the percentage of the team TDs that were Pass TDs by a player.                                                                                                                                                                              | Pass TDs/TM TDs                                                               |
| TDs % of Team TDs**              |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass TDs**               | Counting | pass thrown behind line of scrimmage that results in a touchdown for the offense.                                                                                                                                                           | \-                                                                            |
| Touchdowns**                     |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass                     | Counting | yards gained by offense on a completed pass.                                                                                                                                                                                                | \-                                                                            |
| Yards**                          | Yds, Pass YDs**            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Pass                           | **Pass                     | Metric   | the percentage of the team yards that were Pass YDs by a player.                                                                                                                                                                            | Pass YDs/TM YDs                                                               |
| Yards % of Team Yards**          | Yds % of TM YDs**          |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **NCAA                           | **-**                      | Metric   | A passing metric designed to measure QB performance.                                                                                                                                                                                        | ((8.4\*Pass Yds)+(330\*Pass TDs)+(100\*Pass Comp)-(200\*INTs))/Pass ATT       |
| Passing Efficiency**             |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **NFL                            | **-**                      | Metric   | created by Don Smith, Seymour Siwoff, and Don Weiss to provide a standard for comparing QB passing based on completion % per attempt, yards gained per                                                                                      | (((Pass                                                                       |
| Passer Rating**                  |                            |          | attempt, % of TD passes per attempt, and % of INTs per attempt.                                                                                                                                                                             | Comp/Pass ATTs -.3)\*5+(Pass Yds/Pass ATTs -.3)\*.25+(Pass TDs/Pass           |
|                                  |                            |          |                                                                                                                                                                                                                                             | ATTs)\*20+2.375-(INT/Pass ATTs\*25))/6)\*100)                                 |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/Carry                   | Metric   | a stat divided by the number of carries/rush attempts in season/career                                                                                                                                                                      | \-                                                                            |
| Carry (Per Rush Attempt)**       | or /Rush ATT**             |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/GP**                    | Metric   | stat divided by number of games in season/career.                                                                                                                                                                                           | \-                                                                            |
| Game**                           |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/TM                      | Metric   | stat divided by the player's team pass attempts in a season                                                                                                                                                                                 | \-                                                                            |
| Team Pass Attempt**              | Pass ATT**                 |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/TM                      | Metric   | stat divided by the player's team pass touchdowns in a season                                                                                                                                                                               | \-                                                                            |
| Team Pass Touchdown**            | Pass TD**                  |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/Play**                  | Metric   | stat divided by the player's team plays in a season                                                                                                                                                                                         | \-                                                                            |
| Play**                           |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/REC**                   | Metric   | stat divided by number of receptions in a season/career                                                                                                                                                                                     | \-                                                                            |
| Reception**                      |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/TM                      | Metric   | stat divided by player's team rush attempts in a season.                                                                                                                                                                                    | \-                                                                            |
| Team Rush Attempt**              | Rush ATT**                 |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/TM                      | Metric   | stat divided by player's team rush touchdowns in a season.                                                                                                                                                                                  | \-                                                                            |
| Team Rush Touchdown**            | Rush TD**                  |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Per                            | **/Touch**                 | Metric   | stat divided by number of touches in season/career.                                                                                                                                                                                         | \-                                                                            |
| Touch**                          |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Punt                           | **Punt Returns**           | Counting | when a player receives a punt from the opposing team and attempts to advance the                                                                                                                                                            | \-                                                                            |
| Return**                         |                            |          | ball down the field.                                                                                                                                                                                                                        |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Punt                           | **PR TDs**                 | Counting | when a punt return results in a touchdown for the team that receives it.                                                                                                                                                                    | \-                                                                            |
| Return Touchdown**               |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Punt                           | **PR YDs**                 | Counting | the yards a player gains after receiving a punt from the opposing team.                                                                                                                                                                     | \-                                                                            |
| Return Yard**                    |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **QB                             | **QB Pass ATT MS**         | Metric   | the percentage of total team Pass ATTs thrown by a QB                                                                                                                                                                                       | Pass ATT/TM Pass ATT                                                          |
| Pass Attempt Market Share**      |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **QB                             | **QB Pass TD MS**          | Metric   | the percentage of total team Pass TDs thrown by a QB                                                                                                                                                                                        | Pass                                                                          |
| Pass TD Market Share**           |                            |          |                                                                                                                                                                                                                                             | TDs/TM Pass TDs                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **QB                             | **QB Pass YDs MS**         | Metric   | the percentage of total team Pass YDs thrown by a QB                                                                                                                                                                                        | Pass YDs/TM Pass YDs                                                          |
| Pass Yards Market Share**        |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Quarterback                    | **QB BOA**                 | Metric   | Quarterback BOA traditionally is measured as the age a QB first posted a QBR of 50 or higher in college while average 20 action plays per team game. My data for QBR does not go back to 2003 so I came up with a different criteria for QB | "QB Pass ATT MS\> or =50% and \>100 Pass ATTs"                                |
| Breakout Age**                   |                            |          | BOA. QB BOA is when a QB has greater than 50% of their team's passing attempts in a season.                                                                                                                                                 |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Raw                            | **-**                      | Metric   | created by ESPN to measure QB efficiency based on the down, distance, yard line at the snap, and the QBs contribution to the result of the play. Then this is                                                                               | g(Adjusted                                                                    |
| QBR**                            |                            |          | divided by the total QB action plays in the game including penalties.                                                                                                                                                                       | EPA/Action Plays)                                                             |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receiving                      | **REC CD**                 | Metric   | a metric that equally weighs the career last and career best seasons in terms of market share of team receiving yards and receiving touchdowns.                                                                                             | "=((Career                                                                    |
| College Dominator**              |                            |          |                                                                                                                                                                                                                                             | Last REC Yards MS+Career Last REC TDs MS+Career Best REC Yards MS+Career Best |
|                                  |                            |          |                                                                                                                                                                                                                                             | REC Yards MS)/4)                                                              |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receiving                      | **REC                      | Metric   | the percentage of total team receiving TDs by a player.                                                                                                                                                                                     | REC TDs/TM Pass TDs                                                           |
| TD Market Share**                | TD MS**                    |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receiving                      | **REC                      | Counting | a reception that results in a touchdown.                                                                                                                                                                                                    | \-                                                                            |
| Touchdowns**                     | TDs**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receiving                      | **REC                      | Counting | the number of yards gained from the line of scrimmage by a player after catching a forward pass.                                                                                                                                            | \-                                                                            |
| Yards**                          | YDs**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receiving                      | **REC                      | Metric   | the percentage of total team receiving yards by a player.                                                                                                                                                                                   | REC YDs/TM Pass YDs                                                           |
| Yards Market Share**             | YDs MS**                   |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receptions**                   | **REC**                    | Counting | when a player catches and secures possession of a forward pass in bounds.                                                                                                                                                                   | \-                                                                            |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receptions                     | **REC MS**                 | Metric   | the percentage of total team receptions by a player.                                                                                                                                                                                        | REC/TM                                                                        |
| Market Share**                   |                            |          |                                                                                                                                                                                                                                             | Completions                                                                   |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Receptions                     | **REC/TM                   | Metric   | a receiving efficiency metric that measures the number of receptions per team pass attempt                                                                                                                                                  | REC/TM Pass ATT                                                               |
| Per Team Pass ATT**              | Pass ATT**                 |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Relative                       | **RAS**                    | Metric   | a metric created by Kent Lee Platte that can easily and intuitively gauge a player's athletic abilities relative to the position they play                                                                                                  | **-**                                                                         |
| Athletic Score**                 |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Return**                       | **-**                      | Counting | when a player receives a kickoff or punt from the opposing team and attempts to advance the ball down the field.                                                                                                                            | KR+PR                                                                         |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Return                         | **Return                   | Counting | when a kick return or punt return results in a touchdown for the team that receives it.                                                                                                                                                     | KR TDs+PR TDs                                                                 |
| Touchdown**                      | TD**                       |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Return                         | **Return                   | Counting | the yards a player gains after receiving a kickoff or punt from the opposing team                                                                                                                                                           | KR YDs+PR YDs                                                                 |
| Yard**                           | YDs**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Rush                           | **Rush                     | Counting | when a player tries to advance the ball up field getting the ball behind the line                                                                                                                                                           | \-                                                                            |
| Attempt**                        | ATT**                      |          | of scrimmage.                                                                                                                                                                                                                               |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Rush                           | **Rush                     | Metric   | the percentage of total team Rush ATTs by a player.                                                                                                                                                                                         | Rush ATT/TM Rush ATT                                                          |
| Attempt Market Share**           | ATT MS**                   |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Rush                           | **Rush                     | Metric   | the percentage of total team Rush TDs by a player.                                                                                                                                                                                          | Rush TDs/TM Rush TDs                                                          |
| TD Market Share**                | TDs MS**                   |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Rush                           | **Rush                     | Counting | a Rush ATT that results in a touchdown                                                                                                                                                                                                      | \-                                                                            |
| Touchdowns**                     | TDs**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Rush                           | **Rush                     | Counting | number of yards gained when a player carries the football.                                                                                                                                                                                  | \-                                                                            |
| Yards**                          | YDs**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Rush                           | **Rush                     | Metric   | the percentage of total team Rush YDs by a player.                                                                                                                                                                                          | Rush YDs/TM Rush YDs                                                          |
| Yards Market Share**             | YDs MS**                   |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Rushing                        | **Rush                     | Metric   | a metric that equally weighs the career last and career best seasons in terms                                                                                                                                                               | "=((Career                                                                    |
| College Dominator**              | CD**                       |          | of market share of team rushing yards and rushing touchdowns.                                                                                                                                                                               | Last RUSH Yards MS+Career Last RUSH TDs MS+Career Best RUSH Yards MS+Career   |
|                                  |                            |          |                                                                                                                                                                                                                                             | Best RUSH Yards MS)/4)                                                        |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Scrimmage                      | **SCRIM                    | Metric   | a metric that equally weighs the career last and career best seasons in terms                                                                                                                                                               | "=((Career                                                                    |
| College Dominator**              | CD**                       |          | of market share of team scrimmage yards and scrimmage touchdowns.                                                                                                                                                                           | Last SCRIM Yards MS+Career Last SCRIM TDs MS+Career Best SCRIM Yards          |
|                                  |                            |          |                                                                                                                                                                                                                                             | MS+Career Best SCRIM Yards MS)/4)                                             |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Scrimmage                      | **SCRIM                    | Metric   | the percentage of total team scrimmage touchdowns by a player.                                                                                                                                                                              | SCRIM TDs/TM SCRIM TDs                                                        |
| TD Market Share**                | TD MS**                    |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Scrimmage                      | **SCRIM                    | Counting | the total number of rushing touchdowns and receiving touchdowns by a player                                                                                                                                                                 | REC TDs+Rush TDs                                                              |
| Touchdowns**                     | TDs**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Scrimmage                      | **SCRIM                    | Counting | the total number of rushing yards and receiving yards by a player                                                                                                                                                                           | REC YDs+Rush YDs                                                              |
| Yards**                          | YDs**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Scrimmage                      | **SCRIM                    | Metric   | the percentage of total team scrimmage yards by a player.                                                                                                                                                                                   | SCRIM YDs/TM SCRIM YDs                                                        |
| Yards Market Share**             | YDs MS**                   |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **TE                             | **HaSS**                   | Combine  | an athleticism metric developed by Shawn Siegele that creates a metric for tight ends that adjusts a player's 40 time for height.                                                                                                           | (weight\*200)/(40 time\*40 time\*40 time\*40 time)\*(height/76.4)\^2          |
| Height Adjusted Speed Score**    |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Tight                          | **TE                       | Metric   | the age in a season a tight end first achieves a greater than 15% receiving dominator rating.                                                                                                                                               | "TE CD\> or =15%"                                                             |
| End Breakout Age**               | BOA**                      |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Total                          | **TANY/A**                 | Metric   | a schedule-adjusted, rushing-inclusive version of ANY/A or adjusted net yet yards per passing attempt created by Sean Slavin. My version does not adjust for sacks because my college data doesn't have sacks and sack yards.               | (Total Yards+20\* Total TDs-45\*INTs)/Total Attempts                          |
| Adjusted Net Yards Per Attempt** |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Total                          | **Total                    | Metric   | a metric designed to represent a QBs production based on the percentage the QB had of team Rush YDs, Rush TDs, Pass YDs, and Pass TDs weighed equally.                                                                                      | ((Pass                                                                        |
| QB Market Share**                | QB MS**                    |          |                                                                                                                                                                                                                                             | YDs/TM Pass Yds)/2)+((Pass TDs/TM Pass TDs)+(Rush YDs/TM Rush Yds)/2)+((Rush  |
|                                  |                            |          |                                                                                                                                                                                                                                             | TDs/TM Rush TDs)/4)                                                           |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Total                          | **-**                      | Metric   | created by ESPN to measure QB efficiency based on the down, distance, yard line at the snap, and the QBs contribution to the result of the play. Then this is                                                                               | ???                                                                           |
| QBR**                            |                            |          | divided by the total QB action plays in the game including penalties. This is then adjusted for play difficulty and the quality of opposing defenses.                                                                                       |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Total                          | **Total                    | Counting | the total amount of rush touchdowns, receiving touchdowns, kick return                                                                                                                                                                      | SCRIM                                                                         |
| Touchdowns**                     | TDs**                      |          | touchdowns, and punt return touchdowns for a player.                                                                                                                                                                                        | TDs+Return TDs                                                                |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Total                          | **-**                      | Counting | the total amount of rush attempts, receptions, kick returns, and punt returns for                                                                                                                                                           | Touches+Returns                                                               |
| Touches**                        |                            |          | a player.                                                                                                                                                                                                                                   |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Total                          | **Total                    | Counting | the total amount of rush yards, receiving yards, kick return yards, and punt return yards for a player.                                                                                                                                     | SCRIM                                                                         |
| Yards**                          | YDs**                      |          |                                                                                                                                                                                                                                             | YDs+Return YDs                                                                |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Touch                          | **Touch                    | Metric   | the percentage of total team touches by a player.                                                                                                                                                                                           | Touches/TM                                                                    |
| Market Share**                   | MS**                       |          |                                                                                                                                                                                                                                             | Plays                                                                         |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Touchdown:Interception         | **TD:INT                   | Metric   | Pass TDs divided by Interceptions                                                                                                                                                                                                           | Pass TDs/INT                                                                  |
| Ratio**                          | Ratio**                    |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Touches**                      | **-**                      | Counting | the total number of receptions and rush attempts by a player                                                                                                                                                                                | REC+Rush ATT                                                                  |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Vertical                       | **Vert**                   | Combine  | measures a player's ability to jump off the ground from a flat-footed stance.                                                                                                                                                               | \-                                                                            |
| Jump**                           |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Weight**                       | **-**                      | Combine  | the body's relative mass or the quantity of matter contained by it                                                                                                                                                                          | \-                                                                            |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Weight                         | **WaSS**                   | Combine  | an athleticism metric developed by Bill Barnwell in Pro Football Prospectus that adjusts a player's 40 yard dash time for their weight.                                                                                                     | "=(weight\*200)/(40                                                           |
| Adjusted Speed Score**           |                            |          |                                                                                                                                                                                                                                             | time\*40 time\*40 time\*40 time)"                                             |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Wide                           | **WR BOA**                 | Metric   | the age in a season a wide receiver first achieves a greater than 20% (30% Shawn                                                                                                                                                            | "REC DOM\>20% (30%)"                                                          |
| Receiver Breakout Age**          |                            |          | Siegele) receiving dominator rating.                                                                                                                                                                                                        |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **WR                             | **HaSS**                   | Combine  | an athleticism metric developed by Shawn Siegele that creates a metric for wide receivers that adjusts a player's 40 time for height.                                                                                                       | (weight\*200)/(40 time\*40 time\*40 time\*40 time)\*(height/73.5)\^2          |
| Height Adjusted Speed Score**    |                            |          |                                                                                                                                                                                                                                             |                                                                               |
+----------------------------------+----------------------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+

The most difficult part of working with this dataset, is determining what to do with the missing data in each scenario. Almost every row of data has at least one missing value. The reasons for this vary, but common reasons include, the player was injured and missed a season, the player retired and stopped playing during the period of time this dataset contains, the player was drafted and played a season and then didn't play after that or didn't play for several seasons because more seasoned players were ahead of them on the team. For the majority of these cases, the missing values can be filled with 0's because the player truly didn't have a metric.

One area where I decided not to fill missing values with zero was the columns related to the combine tests. Combine results are heavily utilized when players are being drafted and so I am making an assumption that they will be important to the predictive power of our model. It is fairly common for players to miss certain tests within the combine (due to injury, for example), so they may have values for some metrics but not others. A smaller population opt to not take part in the combine, while others may be injured and can't participate.

Because most of the players have values for several of the combine metrics, I assume that players with recorded values in certain metrics may also have similar values in other metrics. For this reason, I am imputing these missing values using predictive mean matching (pmm).

The other struggle was the sheer number of columns within this dataset. Working through 600+ columns is unrealistic, so other methods were needed to determine how to reduce the dimensionality of the dataset.

## Statistical Methods

As dimensionality is an issue with this dataset, two method of dimensionality reduction will be performed to determine the method that produces the most accurate model. First, I'm exploring using lasso regression in order to set some of the less important variable coefficients to zero. Second, the use of PCA will be explored to drastically reduce the size of the dataset.

Our variable of interest will be a variable called "Break Out" that indicates whether a player averages 10 fantasy football points a game or not. The field will be a Yes/No field.

When generating the predictions for this field, it will be useful to also be able to see not only the classification, but the associated probability of that classification so that we can raise or lower the threshold as needed when we tune our model.

Because this is a classification problem, I will test most of the well known algorithms to see which model produces the most accurate results. I will explore:

-   Random Forest

-   K-Nearest Neighbors

-   Support Vector Machines (SVM)

-   XGBOOST

-   Naive Bayes (only if time permits)

Ultimately, the goal of this project is to develop a model that can predict which receivers will average 10 fantasy football points per game with 80% accuracy. That being said, accuracy will be the metric I use for my evaluation criteria. However, in addition to accuracy, I'll also show common classification metrics such as Precision, Sensitivity, and Specificity.

## Discussion of Results

I will compare my model results here in a neat, organized table.

## Conclusion

Summarize results.

## References

Hampton, B. (2020, May 24). *Blake's Predictive 2020 Wide Receiver Model*. Retrieved from The Undroppables: <https://www.theundroppables.com/blakes-predictive-2020-wide-receiver-model/>

Lindsey, J. (2016, January 13). *The NFL Is Finally Tapping Into the Power of Data*. Retrieved from Wired: <https://www.wired.com/2016/01/the-nfls-impending-data-revolution/>

Subramanian, P. (2014, August 29). *The 3 biggest prizes in fantasy football*. Retrieved from Yahoo Finance: <https://www.yahoo.com/entertainment/news/the-3-biggest-prizes-in-fantasy-football-174712081.html>

Wright, D. (n.d.). *DAVID WRIGHT*. Retrieved from
<https://dynastyleaguefootball.com/author/spacemnspiff207/:>
<https://dynastyleaguefootball.com/author/spacemnspiff207/>

## Appendix 
